version: '2'
services:
  itrm-api:
    build: .
    ports:
      - "50051:4000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mongo:3.5
    volumes:
      - ./data:/data/db
